### ISSUE TITLE
Fix error when adding domain after a previous domain was editied and "Applied"

### ISSUE THREAD

**Issue by jkosinski** [crosslinks/XlinkAnalyzer#9]
To reproduce:
- Load PolI.json
- Click Domains
- Add a domain
- Edit the domain (whatever, range or color)
- Click "Apply" button
- Add another domain:
  Crashes with:
  AttributeError Exception in Tk callback
  Function: <function _onAdd at 0xb06f050> (type: <type 'function'>)
  Args: ()
  Traceback (innermost last):
  File "/struct/cmueller/kosinski/software/UCSF-Chimera64-1.9/lib/python2.7/site-packages/Pmw/Pmw_1_3_3/lib/PmwBase.py", line 1747, in **call**
    return apply(self.func, args)
  File "/struct/cmueller/kosinski/devel/XlinkAnalyzer/xlinkanalyzer/gui.py", line 1678, in _onAdd
    _updateList()
  File "/struct/cmueller/kosinski/devel/XlinkAnalyzer/xlinkanalyzer/gui.py", line 1629, in _updateList
    compVar.set(d.comp.name)
  AttributeError: 'NoneType' object has no attribute 'name'

**Comment by LimpingTwerp** [comment]
Fixed and Tested.

**Comment by crosslinks** [comment]
Thanks! But I think you forgot to push, let me know after you do it, and I will test.
